name: Prepare Indikatoren
on:
  schedule:
    - cron: '34 2 * * *'
  workflow_dispatch:
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          apt-get update -qq && apt-get install -y libudunits2-dev
      - name: Execute Script
        run: Rscript 03_prepare_indikatoren.R
      - name: Set up Git
        run: |-
          git config --global --add safe.directory /__w/0/0
          git config --global user.name "GitHub Actions"
          git config --global user.email "username@users.noreply.github.com"
      - name: Check if there are changes to commit
        id: changes_check
        run: |-
          git add .
          if git diff-index --quiet HEAD; then
             echo "changes=false" >>$GITHUB_OUTPUT
          else
             echo "changes=true" >> $GITHUB_OUTPUT
          fi
      - name: Commit changes
        if: ${{ steps.changes_check.outputs.changes == 'true' }}
        run: git commit -m "Automated changes by GitHub Actions"
      - name: Push changes
        if: ${{ steps.changes_check.outputs.changes == 'true' }}
        run: git push
    container: rocker/tidyverse:4.3.3
